# Change baseurl before deploy
baseurl: "https://liborburda.github.io"
languageCode: "en-us"
paginate: 10
title: "Libor Burda"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
DefaultContentLanguage: "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

module:
  hugoVersion:
    extended: true
    min: "0.87.0"
  imports:
    path: "github.com/CaiJimmy/hugo-theme-stack/v3"

params:
  # Pages placed under these sections will be shown on homepage and archive page.
  mainSections: ["posts"]
  # Output page's full content in RSS.
  rssFullContent: true
  favicon: "/favicon.ico"

  footer:
    since: 2022
    customText: ""

  dateFormat:
    published: "Jan 02, 2006"
    lastUpdated: "Jan 02, 2006 15:04 MST"

  sidebar:
    emoji: ""
    subtitle: ".github.io"
    compact: true
    avatar:
      enabled: true
      local: true
      src: "img/avatar.png"

  article:
    math: false
    readingTime: true

    license:
      enabled: true
      default: "Licensed under CC BY-NC-SA 4.0"

  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

  opengraph:
    twitter:
      # Your Twitter username
      site:
      # Available values: summary, summary_large_image
      card: summary_large_image

  defaultImage:
      opengraph:
          enabled: false
          local: false
          src:

  colorScheme:
      # Display toggle
      toggle: true
      # Available values: auto, light, dark
      default: dark

  imageProcessing:
      cover:
          enabled: true
      content:
          enabled: true

  comments:
    enabled: true
    provider: "giscus"
    giscus:
      repo: "liborburda/liborburda.github.io"
      repoID: "R_kgDOIHWS8g"
      category: "General"
      categoryID: "DIC_kwDOIHWS8s4CRwZM"
      mapping: "pathname"
      lightTheme: ""
      darkTheme: ""
      reactionsEnabled: 1
      emitMetadata: 0

markup:
  # Markdown renderer configuration
  goldmark:
    renderer:
      unsafe: false

  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2

  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4

menu:
  main: []
  social:
    - identifier: "github"
      name: "GitHub"
      url: "https://github.com/liborburda"
      params:
        icon: "brand-github"

    - identifier: "linkedin"
      name: "LinkedIn"
      url: "https://www.linkedin.com/in/liborburda"
      params:
        icon: "brand-linkedin"

permalinks:
  # Permalinks format of each content section
  post: "/p/:slug/"
  page: "/:slug/"

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200
